### ISSUE TITLE
[Suggestion] Avoid spawning wraiths in the rain

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Mobs#165]
The fire from a wraith's attack is put out by rain making them a cakewalk during wet weather. Perhaps they should avoid spawning when it's raining similar to endermen?

**Comment by Thelnfamous1** [comment]
Wraith Fire, according to [the Wraith's entry in the Minecraft Dungeons wiki](https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Wraith), is actually "ice flames". Due to this revelation, I have "inverted" the Wraith Fire to deal Frost damage and not be extinguished by water or rain. It will, however, be extinguished by fire.
