### ISSUE TITLE
[Issue/Suggestion]

### ISSUE THREAD

**Issue by SyrusWhite** [Thelnfamous1/Dungeons-Mobs#18]
Hello,
First things first, Thank you for taking the time to make this amazing mod. It has liven up the battle aspects of  our server and I just want to say thank you. On another note, a player wheres the armor that burns enemies within a certain range every second. I have PVP disabled for our server but that Enchant also affects other players close by. Is there a way to fix this or disable it to affect players when pvp is disabled?

**Comment by Thelnfamous1** [comment]
This is an issue for Dungeons Gear, not Dungeons Mobs. Regardless, there is a config option in Dungeons Gear to disable effects targeting players. In the next release, it will be off by default since so many people ask if the option exists (although I hope I don't get an influx of the opposite, "How can we get the effects to target players"?)
