### ISSUE TITLE
WraithFireBlock incompatible with Infernal Expansion

### ISSUE THREAD

**Issue by LudoCrypt** [Thelnfamous1/Dungeons-Mobs#60]
In the WraithFireBlock class, you're overriding the entityInside class, though, according to the logic there, it looks like there is absolutely no point in doing so. When you are overriding the method, and not calling the super function, its causing incompatibilities with Infernal Expansion. According to the logic i see, if the entity is not fire immune, or if it is a wraith entity, to burn them. This doesnt make sense, because the wraith entity is already not fire immune, so the check does absolutely nothing and the whole method is practically pointless. You should be able to remove it and everything will work exactly the same, and it will fix incompat with Infernal Expansion!
Edit: my apologies if i sound condescending or rude in any way; I just want to help out!

**Comment by Thelnfamous1** [comment]
So the code is supposed to have the purpose of not burning Wraiths in order to prevent it from accidentally killing Wraiths who summon it. Seems the logic is currently not written correctly, but we still do need that method override. We'll see if we can find another means of preventing wraiths from being wraith fire immune.

**Comment by Patrigan** [comment]
Rewritten wraith, should no logner be an issue.
